name: Trigger auto deployment for mycontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mycontainer-AutoDeployTrigger-d04f6354-bb31-4dec-9129-bae316415d2d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.MYCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mycontainer
          resourceGroup: olt-feb
          imageToBuild: mkonda007/mycontainer:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


